let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "FC-24",
    price: 9000,
    desc: "Dive into the digital realm of FC 24 – where fantasy becomes reality, and gamers become legends",
    img: "productssale/fc-24.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "GTA V",
    price: 8000,
    desc: "Experience more than gaming and get into the reality",
    img: "productssale/Gta5.jpg",
  },
  {
    id: "wuefbncxsn",
    name: "Spiderman",
    price: 5000,
    desc: "Unleash your inner superhero shopper – our deals are super-powered!",
    img: "productssale/Spideraman.jpg",
  },
  {
    id: "thyfhcbbcv",
    name: "Need For Sped Heat",
    price: 4000,
    desc: "Gear up for the ultimate shopping race – where speed meets savings!",
    img: "productssale/nfs-heat.jpg",
  },
  {
    id: "yur873hfi",
    name: "Need For Speed Unleash",
    price: 3900,
    desc: "Feel the rush of speed, feel the rush of savings – shop like a champion!",
    img: "productssale/nfs-unleash.jpg",
  },
  {
    id: "hd4wropls",
    name: "Need For Speedd Rivals",
    price: 6000,
    desc: "Shift into high gear and accelerate your way to unbeatable prices",
    img: "productssale/nfs-rivals.jpg",
  },
  {
    id: "hd4wropds",
    name: "MineCraft",
    price: 9000,
    desc: "Explore, build, survive – welcome to the endless adventure of Minecraft!",
    img: "productssale/Minecraft.jpg",
  },
  {
    id: "hddwropls",
    name: "God Of War",
    price: 7000,
    desc: "Embark on a journey where gods clash, and legends are forged.",
    img: "productssale/godofwar.jpg",
  },
  {
    id: "hd49ropls",
    name: "CyberPunk",
    price: 9000,
    desc: "Your transactions, your rules. Welcome to the Cybermall",
    img: "productssale/cyberpunk.jpg",
  },
  {
    id: "hd4wtopls",
    name: "Need For Speed Payback",
    price: 8000,
    desc: "Unleash the roaring engines, the screeching tires",
    img: "productssale/nfs-payback.jpg",
  },
  {
    id: "hd4wroplq",
    name: "Call Of Duty",
    price: 7000,
    desc: "Gear up, soldier! Your gaming mission awaits – victory is just a click away",
    img: "productssale/callofduty.jpg",
  },
  {
    id: "pd4wroplq",
    name: "Call Of Duty MIW",
    price: 9000,
    desc: "Immerse yourself in the epic battleground of savings, where every purchase is a victory royale, MIW style",
    img: "productssale/miw.webp",
  },
];
